<?php 
function faction() {
    $la_faction = array("Des assassins", "Un seigneur élémentaire", "Des brigands", "Un seigneur noble", "Des fées", "Un sorcier", "Des ogres", "Un spectre", "Des kourganes", 
    "Des pèlerins", "Un sphinx", "Les autorités d’une cité", "Un tabergiste", "Titan&Fils", "Un temple", "Un chamane", "Un type tout seul", "Un chevalier", "Un village", 
    "Un clerc", "Un village d’hommes-lézards", "Un démon majeur", "Un voleur", "Un doppelgänger", "Une abomination", "Un ettercap", "Une araignée géante ancienne", 
    "Un grand dragon", "Une bande de gobelins", "Un groupe de kobolds", "Une compagnie de hobgobelins", "Un guerrier", "Une dryade noire", "Un magicien", "Une famille de géants", 
    "Un rakshasa", "Une guenaude", "Un roi orque", "Une guilde de voleurs", "Un seigneur du désordre", "Une guilde marchande");
    
    $que_veut_la_faction = array("La Construction : La faction veut édifier ou organiser une structure physique ou sociale destinée à durer.", 
    "Le Contrôle : La faction veut contrôler une ressource pour s’en assurer le monopole, en gérer la rareté ou au contraire la diffuser ou la détruire.", 
    "La Destruction : La faction veut faire disparaître une cible spécifique – une faction, un peuple, des connaissances, et ainsi de suite.", 
    "La Dissimulation : La faction s’emploie à cacher des savoirs, des objets ou des personnes spécifiques.", 
    "La Domination : La faction veut conquérir le pouvoir ou l’exerce déjà et veut le conserver.", 
    "L'Opposition : La faction existe pour s’opposer directement à une ou plusieurs autres factions spécifiques.", 
    "La Possession : La faction veut s’emparer d’un objet, d’un lieu ou d’une personne et en garder le contrôle.", 
    "La Protection : La faction défend un objet, un lieu, une personne, des connaissances contre d’autres factions qui veulent s’en emparer ou les détruire.", 
    "La Révélation : La faction s’emploie à révéler des secrets ou des connaissances, à découvrir des savoirs perdus ou dissimulés.", 
    "Rien : La faction n’a pas d’agenda spécifique mais agit seulement pour protéger ses intérêts, préserver le statu quo, saisir des opportunités ou satisfaire son bon plaisir.");

    $pourquoi_le_veut_elle = array("pour l'Approbation : La faction cherche à être reconnue, aimée et appréciée.", 
    "pour le Chaos : La faction ne cherche pas le pouvoir, seulement le désordre.", 
    "pour le Conservatisme : La faction veut protéger ses intérêts et les structures actuelles.", 
    "par Cupidité : La faction aime et désire les richesses sous toutes ses formes.", 
    "pour la Curiosité : La faction veut savoir, qu’importe les conséquences.", 
    "par Désespoir : La faction a déjà perdu et plus rien n’a d’importance.", 
    "par Fanatisme : La faction travaille pour des instances supérieures.", 
    "par Folie : La faction suit des logiques incompréhensibles.", 
    "pour l'Immortalité : La faction veut laisser sa trace dans l’histoire.", 
    "par Intolérance : La faction est motivée par la haine et la peur des autres.", 
    "par Jalousie : La faction veut ce que d’autres possèdent.", 
    "par Malveillance : La faction est simplement méchante, très méchante.", 
    "pour la Paix : La faction veut ramener la paix et la tranquillité.", 
    "pour le Pouvoir : La faction veut soumettre le monde à son contrôle.", 
    "pour le Renouveau : La faction veut abattre les anciennes structures pour de nouvelles.", 
    "pour la Revanche : La faction veut se venger ou rétablir une injustice.", 
    "pour Secourir : La faction veut sauver quelque chose ou quelqu’un.", 
    "par Supériorité : La faction est persuadée être meilleure que quiconque.", 
    "pour la Transformation : La faction veut transformer le monde à son idée ou son image.", 
    "pour se rendre Utile : La faction veut qu’on ait besoin d’elle, toujours.");

    $atouts_de_la_faction = array("Alliances : La faction peut compter sur l’aide de ses alliés.", 
    "Capacités et compétences personnelles : Les membres de la faction sont individuellement puissants et bien entraînés.", 
    "Chance insolente : La faction voit toutes les coïncidences tourner en sa faveur.", 
    "Communication et déplacements : Les membres de la faction peuvent communiquer en temps réel et se déplacer à grande vitesse, donnant l’impression qu’ils sont partout en même temps.", 
    "Cruauté insensible : La faction n’a aucune espèce de remord à utiliser tous les moyens nécessaires.", 
    "Discrétion : La faction ou ses membres sont impossibles à déceler, à dévoiler au grand jour ou à localiser.", 
    "Grande intelligence : La faction fait toujours les meilleurs choix possibles.", 
    "Initiative : La faction est toujours au taquet pour réagir.", 
    "Planification : La faction use de complots et d’intrigues complexes pour conduire ses plans, avec de nombreuses sécurités.", 
    "Pouvoir économique : La faction possède une richesse fabuleuse et quasiment inépuisable, qui lui permet de tout acheter.", 
    "Pouvoir légal : La faction possède la légitimité et bénéficie de la protection des lois et de ses représentants.", 
    "Pouvoir magique : La faction a accès à toutes sortes de sorts, de rituels, de portails, d’objets magiques et d’invocations.", 
    "Pouvoir religieux : La faction possède la légitimité religieuse et a accès à la puissance magique des divinités.", 
    "Protections : Les membres et les ressources de la faction sont très bien protégés.", 
    "Psychologie : La faction comprend les motivations et l’état d’esprit de ses adversaires et prévoit leurs mouvements.", 
    "Refuge : La faction a toujours des positions de repli en cas de revers.", 
    "Réserve matérielle : La faction a accès à toutes sortes de ressources matérielles : armes, outils, chariots, bateaux, refuges, matériaux, ressources naturelles et ainsi de suite.", 
    "Secrets : La faction est dangereuse à cause de ce qu’elle sait et de ce qu’elle peut apprendre par ses espions, ses informateurs ou la magie.", 
    "Suivants loyaux : La faction est servie par des agents extrêmement loyaux, par conviction ou fanatisme.", 
    "Support militaire : La faction a accès à une armée, des mercenaires, des aventuriers ou des créatures dangereuses.");

    $faiblesses_de_la_faction = array("Conflits : La faction est divisée sur les objectifs et les moyens.", 
    "Distance : Les dirigeants de la faction sont loin et ilest difficile pour eux d’agir ou de réagir. Ilsdoivent se fier à leurs agents locaux.", 
    "Ignorance : La faction n’a pas les bonnes informations ou a du mal à se tenir au courant.", 
    "Imbécilité : La faction est bête, mais bête !", 
    "Improvisation : La faction ne prévoit jamais rien et secontente de réagir aux évènements.", 
    "Impulsivité : La faction agit souvent sans réfléchir.", 
    "Incompétence : Les membres de la faction ne sont pas trèsbons ou ne possèdent pas les connaissanceset les compétences utiles à leurs projets.", 
    "Indécision : La faction n’ose rien et hésite toujours à prendre des décisions fermes.", 
    "Lenteur : La faction réagit toujours très lentement auxévènements, par défaut de communication rapide.", 
    "Maladresse : La faction rate des trucs pourtant faciles.", 
    "Malchance : La faction n’a jamais de chance.", 
    "Misère : La faction n’a que de faibles moyens matériels et peu de richesses disponibles.", 
    "Obligations : La faction est tenue par l’honneur ou des obligations contraignantes.", 
    "Orgueil : La faction est pétrie de vanité et de suffisance.", 
    "Personnel : La faction possède très peu de membres et ils ne peuvent être partout.", 
    "Renommée : La faction est connue de tout le monde et ses actions toujours largement commentées.", 
    "Responsabilité : La faction doit protéger quelque chose ou quelqu’un et cela mobilise nombre de ses ressources.", 
    "Secret : La faction doit absolument protéger un secret qui signifierait sa perte.", 
    "Trahison : La faction abrite un traitre.", 
    "Vulnérabilité : La faction est fragile et il est aisé d’atteindre ses membres ou ses ressources.");
}

?>